# Generated by Django 2.2.9 on 2020-01-22 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0002_auto_20200122_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='channel',
            field=models.CharField(default=uuid.UUID('8d78c207-0f83-48e7-8bad-729fbdca0274'), max_length=100, unique=True),
        ),
    ]
