# Generated by Django 2.2.9 on 2020-01-22 17:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0003_auto_20200122_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='channel',
            field=models.CharField(default=uuid.UUID('f6745600-a43c-4edb-9c6a-faae6e98528e'), max_length=100, unique=True),
        ),
    ]
