# Generated by Django 2.2.9 on 2020-01-23 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0005_auto_20200123_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='channel',
            field=models.CharField(default=uuid.UUID('57e808cb-7a44-4836-9d3b-e2f907cba9b8'), max_length=100, unique=True),
        ),
    ]
