# Generated by Django 2.2.7 on 2019-12-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strainers', '0002_auto_20191219_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='straining',
            name='statuscode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='straining',
            name='statusmessage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
