version: "3.4"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data/
    env_file:
      - deployment.env
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  redis:
    image: redis:latest
  web:
    image: jhnnsrs/bergen:dask
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - arnheim.env
      - deployment.env
    volumes:
      - ./bergen:/code
      - ./media:/code/media
      - ./files:/code/files
    links:
      - redis
      - worker
  worker:
    image: jhnnsrs/bergen:dask
    command: python manage.py runallworkers
    env_file:
      - arnheim.env
      - deployment.env
    volumes:
      - ./bergen:/code
      - ./media:/code/media
      - ./files:/code/files
    links:
      - redis
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx-production.conf:/etc/nginx/nginx.conf
      - ./media:/media
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./bergen/static_collected:/opt/static
    ports:
      - 80:80
      - 443:443
    links:
      - web
      - worker
      - notebook
      - daskscheduler
      - certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  notebook:
    image: jhnnsrs/jupjup:latest
    command: jupyter lab --port=90 --ip=0.0.0.0 --allow-root --notebook-dir=/notebooks/
    environment:
      - HOME=home
      - DASK_SCHEDULER_ADDRESS="tcp://daskscheduler:8786"
    env_file:
      - arnheim.env
      - deployment.env
    volumes:
      - ./notebooks:/notebooks
      - ./bergen:/code/
      - ./jupjup:/config/
      - ./media:/code/media
      - ./files:/code/files
    ports:
      - 90:90
    links:
      - web
      - worker
      - daskscheduler
  daskscheduler:
    image: jhnnsrs/dask:latest
    ports:
      - "8786:8786"
      - "8787:8787"
    command: dask-scheduler --dashboard-prefix=daskboard
  daskworker:
    image: jhnnsrs/dask:latest
    command: ["dask-worker", "tcp://daskscheduler:8786"]
    volumes:
      - ./media:/code/media
      - ./files:/code/files

volumes:
  postgres_data:
  dbdata:
