version: "3.4"


services:
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx-configuration.conf:/etc/nginx/nginx.conf
      - media:/media/
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    links:
      - web
      - worker
      - certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  vscode:
  dbdata:
  media:
  files:
