version: "3.4"

services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
  web:
    build: bergen
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_LOG_LOVEL=INFO
    volumes:
      - ./bergen:/code
      - ./database:/code/db
      - media:/code/media/
    ports:
      - "8000:8000"
    links:
      - redis
      - worker
      - db
  worker:
    build: bergen
    command: python manage.py runworker channels maxisp bioconverter nifti image test prewitt linerect transformimage aisdata analyzer slicedmaxisp mapping sliceline kafka kafkain masker clusterdata pandas profiler excelexport importer
    volumes:
      - ./bergen:/code
      - media:/code/media/
      - ./database:/code/db
      - files:/code/files/
    links:
      - redis
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - media:/media/
    ports:
      - 80:80
      - 443:443
    links:
      - web
      - worker
  notebook:
    build: jupjup
    command: jupyter lab --port=90 --ip=0.0.0.0 --allow-root --notebook-dir=/notebooks/
    environment:
      - HOME=home
    volumes:
      - ./notebooks:/notebooks
      - ./bergen:/code/
      - ./jupjup:/config/
      - media:/code/media/
      - files:/files/
    ports:
      - "90:90"

volumes:
  vscode:
  dbdata:
  media:
    driver_opts:
      type: none
      device: /c/Programme/Trontheim/arnheim/media
      o: bind
  files:
    driver_opts:
      type: none
      device: /c/Data/Files
      o: bind
