version: "3.4"

services:
  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgresdata:/var/lib/postgresql/data/
    env_file:
      - arnheim.env
  redis:
    image: redis:latest
  arbeider:
    image: jhnnsrs/arbeider:base
    command: python manage.py runallworkers
    environment:
      - ARNHEIM_MODULES=filters
    env_file:
      - arnheim.env
      - development.env
    volumes:
      - ./bergen/filters:/code/filters
      - ./bergen/larvik:/code/larvik
      - ./bergen/elements:/code/elements
      - media:/code/media
    links:
      - postgres
      - redis
  extended:
    image: jhnnsrs/arbeider:extensive
    command: python manage.py runallworkers
    environment:
      - ARNHEIM_MODULES=drawing,metamorphers,transformers
    env_file:
      - arnheim.env
      - development.env
    volumes:
      - ./bergen/metamorphers:/code/metamorphers
      - ./bergen/drawing:/code/drawing
      - ./bergen/transformers:/code/transformers
      - ./bergen/larvik:/code/larvik
      - ./bergen/elements:/code/elements
      - media:/code/media
    links:
      - postgres
      - redis
  javarbeiter:
    image: jhnnsrs/arbeider:java
    command: python manage.py runallworkers
    environment:
      - ARNHEIM_MODULES=bioconverter,importer
    env_file:
      - arnheim.env
      - development.env
    volumes:
      - ./bergen/bioconverter:/code/bioconverter
      - ./bergen/importer:/code/importer
      - ./bergen/larvik:/code/larvik
      - ./bergen/elements:/code/elements
      - media:/code/media
      - files:/code/files
    links:
      - postgres
      - redis
  web:
    image: jhnnsrs/bergen:base
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - arnheim.env
      - development.env
    volumes:
      - ./bergen:/code
      - media:/code/media
    links:
      - postgres
      - redis
  oslo:
    image: jhnnsrs/bergen:base
    command: python manage.py runoslo
    env_file:
      - arnheim.env
      - development.env
    volumes:
      - ./bergen:/code
      - media:/code/media
    links:
      - redis
      - web
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - media:/media
    logging:
      driver: none
    ports:
      - 80:80
      - 443:443
    links:
      - web
      - oslo
      - notebook
      - daskscheduler
  notebook:
    image: jhnnsrs/jupjup:latest
    command: jupyter lab --port=90 --ip=0.0.0.0 --allow-root --notebook-dir=/notebooks/
    environment:
      - HOME=/config
      - DASK_SCHEDULER_ADDRESS="tcp://daskscheduler:8786"
    env_file:
      - arnheim.env
      - development.env
    volumes:
      - ./notebooks:/notebooks
      - ./bergen:/code/
      - ./jupjup/.config/dask:/config/.config/dask
      - media:/code/media
    ports:
      - 90:90
    links:
      - web
      - oslo
      - daskscheduler
  daskscheduler:
    image: jhnnsrs/dask:latest
    ports:
      - "8786:8786"
      - "8787:8787"
    command: dask-scheduler --dashboard-prefix=daskboard
  daskworker:
    image: jhnnsrs/dask:latest
    command: ["dask-worker", "tcp://daskscheduler:8786", "--local-directory=/tmp"]
    volumes:
      - ./bergen:/code
      - media:/code/media

volumes:
  vscode:
  postgresdata:
  media:
    driver_opts:
      type: none
      device: /c/Users/jhnns/PycharmProjects/arnheim/media
      o: bind
  files:
    driver_opts:
      type: none
      device: /c/Users/jhnns/PycharmProjects/arnheim/files
      o: bind
