version: "3.7"

volumes:
  vscode:
  dbdata:
  media:
    driver_opts:
      type: none
      device: /home/ubuntu/media
      o: bind
  files:
    driver_opts:
      type: none
      device: /home/ubuntu/files
      o: bind
