version: "3.4"

services:
  redis:
    image: redis:latest
  web:
    image: jhnnsrs/bergen:dask
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - arnheim.env
      - development.env
    volumes:
      - ./bergen:/code
      - media:/code/media
      - files:/code/files
    links:
      - redis
      - worker
  worker:
    image: jhnnsrs/bergen:dask
    command: python manage.py runallworkers
    env_file:
      - arnheim.env
      - development.env
    volumes:
      - ./bergen:/code
      - media:/code/media
      - files:/code/files
    links:
      - redis
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - media:/media
      - ./cloud/:/cloud
    ports:
      - 80:80
      - 443:443
    links:
      - web
      - worker
      - notebook
      - daskscheduler
  notebook:
    image: jhnnsrs/jupjup:latest
    command: jupyter lab --port=90 --ip=0.0.0.0 --allow-root --notebook-dir=/notebooks/
    environment:
      - HOME=home
      - DASK_SCHEDULER_ADDRESS="tcp://daskscheduler:8786"
    env_file:
      - arnheim.env
      - development.env
    volumes:
      - ./notebooks:/notebooks
      - ./bergen:/code/
      - ./jupjup:/config/
      - media:/code/media
      - files:/code/files
    ports:
      - 90:90
    links:
      - web
      - worker
      - daskscheduler
  daskscheduler:
    image: jhnnsrs/dask:latest
    ports:
      - "8786:8786"
      - "8787:8787"
    command: dask-scheduler --dashboard-prefix=daskboard
  daskworker:
    image: jhnnsrs/dask:latest
    command: ["dask-worker", "tcp://daskscheduler:8786"]
    volumes:
      - ./bergen:/code
      - media:/code/media
      - files:/code/files

volumes:
  vscode:
  dbdata:
  media:
    driver_opts:
      type: none
      device: /c/Users/jhnns/PycharmProjects/arnheim/media
      o: bind
  files:
    driver_opts:
      type: none
      device: /c/Users/jhnns/PycharmProjects/arnheim/files
      o: bind
