version: "3.7"

services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
  web:
    build: bergen
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./bergen:/code
      - media:/code/media/
    ports:
      - "8000:8000"
    links:
      - redis
      - worker
      - db:db
  worker:
    build: bergen
    command: python manage.py runworker channels maxisp bioconverter nifti image test prewitt linerect transformimage aisdata analyzer slicedmaxisp mapping
    volumes:
      - ./bergen:/code
      - media:/code/media/
    links:
      - redis
  nginx:
    restart: always
    build: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - media:/media/
    links:
      - web
      - worker

volumes:
  vscode:
  dbdata:
  media:
    driver_opts:
      type: none
      device: /c/Users/jhnns/PycharmProjects/arnheim/media
      o: bind
