version: "3.4"

services:
  postgres:
    image: postgres:12.2-alpine
    volumes:
      - nanadata:/var/lib/postgresql/data
    env_file:
      - arnheim.env
  redis:
    image: redis:latest
  javarbeiter:
    image: jhnnsrs/arbeider:java
    command: python /arbeider/manage.py runallworkers
    environment:
      - ARNHEIM_MODULES=bioconverter,importer
    env_file:
      - arnheim.env
      - deployment.env
    volumes:
      - ./arbeider/base/arbeid:/arbeider/arbeid
      - ./bergen/bioconverter:/code/bioconverter
      - ./bergen/importer:/code/importer
      - ./bergen/larvik:/arbeider/larvik
      - ./bergen/elements:/arbeider/elements
      - ./media:/code/media
      - ./files:/code/files
    links:
      - postgres
      - redis
  filters:
    image: jhnnsrs/arnheim-filters
    env_file:
      - arnheim.env
      - development.env
    volumes:
      - media:/code/media
    links:
      - postgres
      - redis
  additions:
    image: jhnnsrs/arnheim-additions
    env_file:
      - arnheim.env
      - development.env
    volumes:
      - media:/code/media
    links:
      - postgres
      - redis
  web:
    image: jhnnsrs/bergen
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - arnheim.env
      - development.env
    volumes:
      - ./bergen:/code
      - media:/code/media
    links:
      - postgres
      - redis
  oslo:
    image: jhnnsrs/bergen
    command: python manage.py runoslo
    env_file:
      - arnheim.env
      - development.env
    volumes:
      - ./bergen:/code
      - media:/code/media
    links:
      - redis
      - web
  verge:
    image: jhnnsrs/verge
    volumes:
      - media:/media
    links:
      - web
    labels:
      - "traefik.http.routers.verge.rule=Host(`localhost`)"
  notebook:
    image: jhnnsrs/jupy:latest
    command: jupyter lab --port=90 --ip=0.0.0.0 --allow-root --notebook-dir=/notebooks/
    environment:
      - HOME=/config
    env_file:
      - arnheim.env
      - development.env
    volumes:
      - ./notebooks:/notebooks
      - ./bergen:/code
      - ./jupy/.config/dask:/config/.config/dask
      - media:/code/media
    links:
      - web
      - oslo
      - daskscheduler
    labels:
      - "traefik.http.routers.notebook.rule=PathPrefix(`/jupyter`)"
      - "traefik.http.services.notebook.loadbalancer.server.port=90"
  daskscheduler:
    image: jhnnsrs/dask:latest
    ports:
      - "8786:8786"
      - "8787:8787"
    command: dask-scheduler --dashboard-prefix=daskboard
    labels:
      - "traefik.http.routers.daskscheduler.rule=PathPrefix(`/daskboard`)"
      - "traefik.http.services.daskscheduler.loadbalancer.server.port=8787"
  daskworker:
    image: jhnnsrs/dask:latest
    command: ["dask-worker", "tcp://daskscheduler:8786", "--local-directory=/tmp"]
    volumes:
      - ./bergen:/code
      - media:/code/media
  minio:
    image: "minio/minio"
    command: server /export
    environment:
      MINIO_ACCESS_KEY: weak_access_key
      MINIO_SECRET_KEY: weak_secret_key
    labels:
      - "traefik.http.routers.minio.rule=PathPrefix(`/minio`) || Host(`minio.localhost`)"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
      - "traefik.http.routers.minios.entrypoints=websecure"
      - "traefik.http.routers.minios.tls=true"
      - "traefik.http.routers.minios.rule=Host(`minio.localhost`)"
    volumes:
        - ./objects:/export
  traefik:
    image: traefik:v2.2
    command:
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.file.directory=/etc/traefik/dynamic_conf
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/certs:ro
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/dynamic_conf/conf.yml:ro
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=jhnnsrs:$$apr1$$xqe3h46w$$7j.Q4aQUwU7UM3uua56Y8/"

volumes:
  vscode:
  nanadata:
  media:
  files:
