FROM jhnnsrs/arbeider:base

# Install Oracle Java 11
RUN apt-get update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64/
RUN export JAVA_HOME

# Install python-bioimage and javabridge
ADD requirements.txt /tmp
WORKDIR /tmp
RUN pip install -r requirements.txt

WORKDIR /code


