# Generated by Django 2.2.5 on 2019-09-10 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drawing', '0005_auto_20190518_1628'),
        ('representations', '0001_initial'),
        ('transformers', '0005_auto_20190910_1335'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeid', models.CharField(blank=True, max_length=400, null=True)),
                ('vectors', models.CharField(max_length=3000)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masks', to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masks', to='representations.Experiment')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masks', to='drawing.Sample')),
                ('transformation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masks', to='transformers.Transformation')),
            ],
        ),
        migrations.CreateModel(
            name='Revamper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('channel', models.CharField(blank=True, max_length=100, null=True)),
                ('defaultsettings', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Revamping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeid', models.CharField(blank=True, max_length=400, null=True)),
                ('settings', models.CharField(max_length=1000)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revamper.Mask')),
                ('revamper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revamper.Revamper')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.Sample')),
                ('transformation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transformers.Transformation')),
            ],
        ),
    ]
