# Generated by Django 2.2.11 on 2020-03-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_remove_sample_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformation',
            name='sample',
        ),
    ]
