# Generated by Django 2.2.5 on 2019-09-21 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import elements.models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_auto_20190920_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='experiment_banner'),
        ),
        migrations.AlterField(
            model_name='numpy',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numpys', to='elements.Sample'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='bioseries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biouploader.BioSeries'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='creator',
            field=models.ForeignKey(on_delete=models.SET(elements.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elements.Experiment'),
        ),
    ]
