# Generated by Django 2.2.5 on 2019-10-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_auto_20190921_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pandas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FilePathField(max_length=400)),
                ('vid', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=100)),
                ('compression', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
