# Generated by Django 2.2.6 on 2019-10-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_auto_20191001_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentalgroup',
            name='iscontrol',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
