# Generated by Django 2.2.9 on 2019-12-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0012_experiment_linked_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='numpy',
            name='iszarr',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
