# Generated by Django 2.2.9 on 2019-12-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0013_numpy_iszarr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zarr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.FilePathField(max_length=600)),
                ('group', models.CharField(max_length=800)),
            ],
        ),
    ]
