# Generated by Django 2.2.9 on 2020-01-22 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biouploader', '0002_auto_20200122_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel', models.CharField(default=uuid.UUID('9e0b6cb4-5ebb-4867-a77c-934a6383cf77'), max_length=100, unique=True)),
                ('settings', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Importing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statuscode', models.IntegerField(blank=True, null=True)),
                ('statusmessage', models.CharField(blank=True, max_length=500, null=True)),
                ('settings', models.CharField(max_length=1000)),
                ('nodeid', models.CharField(blank=True, max_length=400, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.Importer')),
                ('locker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biouploader.Locker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
