# Generated by Django 2.2.7 on 2019-12-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
