# Generated by Django 2.2.7 on 2019-12-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0003_delete_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='importing',
            name='statuscode',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importing',
            name='statusmessage',
            field=models.CharField(default='Done', max_length=500),
            preserve_default=False,
        ),
    ]
