# Generated by Django 2.2.7 on 2019-12-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0004_auto_20191219_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importing',
            name='statuscode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importing',
            name='statusmessage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
