# Generated by Django 2.2.11 on 2020-03-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metamorphers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metamorphing',
            name='sample',
        ),
    ]
