# Generated by Django 2.2.11 on 2020-03-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metamorphers', '0002_remove_metamorphing_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='display',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='sample',
        ),
    ]
