# Generated by Django 2.0.9 on 2019-02-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metamorphers', '0002_remove_metamorpher_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metamorphing',
            name='test',
        ),
    ]
