# Generated by Django 2.0.9 on 2019-03-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamorphers', '0004_auto_20190309_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display',
            name='nifti',
        ),
        migrations.AddField(
            model_name='display',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='representation_images'),
        ),
    ]
