# Generated by Django 2.0.9 on 2019-04-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamorphers', '0005_auto_20190309_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='niftipath',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
