# Generated by Django 2.0.9 on 2019-04-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamorphers', '0006_exhibit_niftipath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='niftipath',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
