# Generated by Django 2.0.9 on 2019-04-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamorphers', '0007_auto_20190405_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='niftipath',
            field=models.FileField(blank=True, null=True, upload_to='nifti'),
        ),
    ]
