# Generated by Django 2.2.5 on 2019-09-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamorphers', '0009_kafkaing'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
