# Generated by Django 2.0.9 on 2019-03-13 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='nodeclass',
            field=models.CharField(default='classic-node', max_length=300),
        ),
        migrations.AlterField(
            model_name='node',
            name='defaultsettings',
            field=models.CharField(max_length=5000),
        ),
    ]
