# Generated by Django 2.0.9 on 2019-03-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_auto_20190313_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='entityid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
