# Generated by Django 2.0.9 on 2019-03-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_node_entityid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='entityid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
