# Generated by Django 2.0.9 on 2019-03-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_auto_20190313_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='type',
            new_name='variety',
        ),
    ]
