# Generated by Django 2.0.9 on 2019-03-19 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nodes', '0005_auto_20190313_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArnheimHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('rooturl', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('expiry_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NodeElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
                ('entity', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NodeVariety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('parser', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=400)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.ArnheimHost')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.NodeType')),
            ],
        ),
        migrations.AddField(
            model_name='nodeelement',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.NodeVariety'),
        ),
    ]
