# Generated by Django 2.0.9 on 2019-03-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0006_auto_20190319_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arnheimhost',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
