# Generated by Django 2.0.9 on 2019-03-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0007_auto_20190319_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.NodeVariety'),
        ),
        migrations.AlterField(
            model_name='nodevariety',
            name='type',
            field=models.CharField(max_length=400),
        ),
        migrations.DeleteModel(
            name='NodeType',
        ),
    ]
