# Generated by Django 2.2.1 on 2019-07-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0009_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='flows',
            field=models.ManyToManyField(to='flow.FilterFlow'),
        ),
    ]
