# Generated by Django 2.2.1 on 2019-07-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0010_auto_20190730_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='layout',
            field=models.TextField(),
        ),
    ]
