# Generated by Django 2.2.1 on 2019-07-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0011_auto_20190730_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignNodeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeid', models.CharField(max_length=100)),
                ('data', models.TextField()),
            ],
        ),
    ]
