# Generated by Django 2.2.5 on 2019-09-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0012_foreignnoderequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='variety',
        ),
    ]
