# Generated by Django 2.2.5 on 2019-09-20 12:49

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drawing', '0002_auto_20190920_1249'),
        ('biouploader', '0001_initial'),
        ('elements', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('transformers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(blank=True, max_length=300, null=True)),
                ('nodeid', models.CharField(blank=True, max_length=400, null=True)),
                ('vid', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=4000)),
                ('items', models.CharField(max_length=600)),
                ('type', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.Experiment')),
                ('roi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='drawing.ROI')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='elements.Sample')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('transformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='transformers.Transformation')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('inputmodel', models.CharField(blank=True, max_length=1000, null=True)),
                ('outputmodel', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(max_length=100)),
                ('channel', models.CharField(blank=True, max_length=100, null=True)),
                ('defaultsettings', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeid', models.CharField(blank=True, max_length=400, null=True)),
                ('override', models.BooleanField()),
                ('settings', models.CharField(max_length=1000)),
                ('error', models.CharField(blank=True, max_length=300, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluators.Evaluator')),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.Experiment')),
                ('roi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.ROI')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Sample')),
                ('transformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transformers.Transformation')),
            ],
        ),
        migrations.CreateModel(
            name='VolumeData',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evaluators.Data')),
                ('b4channel', models.IntegerField()),
                ('aisstart', models.IntegerField()),
                ('aisend', models.IntegerField()),
                ('pixellength', models.IntegerField()),
                ('physicallength', models.FloatField()),
                ('vectorlength', models.FloatField()),
                ('diameter', models.IntegerField()),
                ('threshold', models.FloatField()),
                ('userdefinedstart', models.IntegerField()),
                ('userdefinedend', models.IntegerField()),
                ('intensitycurves', models.CharField(max_length=5000)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biouploader.BioMeta')),
            ],
            bases=('evaluators.data',),
        ),
        migrations.CreateModel(
            name='ClusterData',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evaluators.Data')),
                ('clusternumber', models.IntegerField()),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biouploader.BioMeta')),
            ],
            bases=('evaluators.data',),
        ),
    ]
