# Generated by Django 2.0.9 on 2019-02-05 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('representations', '0001_initial'),
        ('evaluators', '0001_initial'),
        ('transformers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
        ('drawing', '0002_auto_20190205_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluating',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representations.Experiment'),
        ),
        migrations.AddField(
            model_name='evaluating',
            name='roi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.ROI'),
        ),
        migrations.AddField(
            model_name='evaluating',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.Sample'),
        ),
        migrations.AddField(
            model_name='evaluating',
            name='transformation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transformers.Transformation'),
        ),
        migrations.AddField(
            model_name='data',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='data',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representations.Experiment'),
        ),
        migrations.AddField(
            model_name='data',
            name='roi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='drawing.ROI'),
        ),
        migrations.AddField(
            model_name='data',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='drawing.Sample'),
        ),
        migrations.AddField(
            model_name='data',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='data',
            name='transformation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='transformers.Transformation'),
        ),
        migrations.AddField(
            model_name='volumedata',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.BioMeta'),
        ),
    ]
