# Generated by Django 2.0.9 on 2019-02-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0002_auto_20190205_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='inputmodel',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='evaluator',
            name='outputmodel',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='evaluator',
            name='path',
            field=models.CharField(default='pahap', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluator',
            name='channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
