# Generated by Django 2.2.5 on 2019-09-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0002_auto_20190920_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterdata',
            name='clusterarea',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clusterdata',
            name='clusterareapixels',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
