# Generated by Django 2.2.5 on 2019-09-12 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0005_auto_20190518_1628'),
        ('evaluators', '0003_auto_20190208_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterData',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evaluators.Data')),
                ('clusternumber', models.IntegerField()),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.BioMeta')),
            ],
            bases=('evaluators.data',),
        ),
    ]
