# Generated by Django 2.2.5 on 2019-10-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0004_clusterdata_spatialunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='tags',
        ),
    ]
