# Generated by Django 2.2.5 on 2019-09-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0004_clusterdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=4000),
        ),
    ]
