# Generated by Django 2.2.7 on 2019-12-17 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biouploader', '0002_auto_20190921_1033'),
        ('bioconverter', '0004_conversing_status'),
        ('evaluators', '0005_remove_data_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='LengthData',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evaluators.Data')),
                ('pixellength', models.IntegerField()),
                ('physicallength', models.FloatField()),
                ('distancetostart', models.IntegerField()),
                ('physicaldistancetostart', models.FloatField()),
                ('physicaldistancetoend', models.FloatField()),
            ],
            bases=('evaluators.data',),
        ),
        migrations.AddField(
            model_name='data',
            name='biometa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biouploader.BioMeta'),
        ),
        migrations.AddField(
            model_name='data',
            name='representation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bioconverter.Representation'),
        ),
        migrations.AlterField(
            model_name='data',
            name='roi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='drawing.ROI'),
        ),
        migrations.AlterField(
            model_name='data',
            name='transformation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='transformers.Transformation'),
        ),
    ]
