# Generated by Django 2.2.7 on 2019-12-17 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0006_auto_20191217_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusterdata',
            name='spatialunit',
        ),
        migrations.RemoveField(
            model_name='data',
            name='items',
        ),
        migrations.AddField(
            model_name='data',
            name='evaluating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluators.Evaluating'),
        ),
        migrations.AlterField(
            model_name='clusterdata',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biouploader.BioMeta'),
        ),
    ]
