# Generated by Django 2.2.7 on 2019-12-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0007_auto_20191217_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='lengthdata',
            name='distancetoend',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
