# Generated by Django 2.2.7 on 2019-12-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0008_lengthdata_distancetoend'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluating',
            name='statuscode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluating',
            name='statusmessage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
