# Generated by Django 2.0.9 on 2019-02-05 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('representations', '0001_initial'),
        ('filterbank', '0001_initial'),
        ('drawing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numpy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FilePathField()),
                ('position', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.Sample')),
            ],
        ),
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vid', models.CharField(max_length=200)),
                ('nodeid', models.CharField(blank=True, max_length=400, null=True)),
                ('shape', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.CharField(blank=True, max_length=300, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representations.Experiment')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filterbank.AImage')),
                ('numpy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transformers.Numpy')),
                ('representation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filterbank.Representation')),
                ('roi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformations', to='drawing.ROI')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformations', to='drawing.Sample')),
            ],
        ),
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('inputmodel', models.CharField(blank=True, max_length=1000, null=True)),
                ('outputmodel', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(max_length=100)),
                ('channel', models.CharField(blank=True, max_length=100, null=True)),
                ('defaultsettings', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Transforming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.CharField(max_length=1000)),
                ('nodeid', models.CharField(blank=True, max_length=400, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representations.Experiment')),
                ('representation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filterbank.Representation')),
                ('roi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.ROI')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.Sample')),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transformers.Transformer')),
            ],
        ),
    ]
