# Generated by Django 2.2.1 on 2019-07-18 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filterbank', '0004_auto_20190408_1730'),
        ('representations', '0001_initial'),
        ('drawing', '0005_auto_20190518_1628'),
        ('transformers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('inputmodel', models.CharField(blank=True, max_length=1000, null=True)),
                ('outputmodel', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(max_length=100)),
                ('channel', models.CharField(blank=True, max_length=100, null=True)),
                ('defaultsettings', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Masking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.CharField(max_length=1000)),
                ('nodeid', models.CharField(blank=True, max_length=400, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representations.Experiment')),
                ('masker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transformers.Masker')),
                ('roi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.ROI')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.Sample')),
                ('transformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filterbank.Representation')),
            ],
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vid', models.CharField(max_length=200)),
                ('nodeid', models.CharField(blank=True, max_length=400, null=True)),
                ('shape', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.CharField(blank=True, max_length=300, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representations.Experiment')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filterbank.AImage')),
                ('numpy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transformers.Numpy')),
                ('roi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masks', to='drawing.ROI')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masks', to='drawing.Sample')),
                ('transformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transformers.Transformation')),
            ],
        ),
    ]
