# Generated by Django 2.2.7 on 2019-12-16 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformation',
            name='inputtransformation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transformers.Transformation'),
        ),
    ]
