# Generated by Django 2.2.5 on 2019-09-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformers', '0002_mask_masker_masking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numpy',
            name='file',
            field=models.FilePathField(max_length=400),
        ),
    ]
