# Generated by Django 2.2.5 on 2019-09-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformers', '0003_auto_20190910_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformation',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
