# Generated by Django 2.2.7 on 2019-12-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformers', '0003_auto_20191219_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='transforming',
            name='statuscode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transforming',
            name='statusmessage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
