# Generated by Django 2.2.9 on 2020-01-23 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transformers', '0004_auto_20200122_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformer',
            name='channel',
            field=models.CharField(default=uuid.UUID('766608a7-c711-409c-98d7-1a9b1ee34eca'), max_length=100, unique=True),
        ),
    ]
