# Generated by Django 2.2.9 on 2020-01-14 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0014_zarr'),
        ('transformers', '0004_auto_20191219_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformation',
            name='zarr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.Zarr'),
        ),
    ]
