# Generated by Django 2.0.9 on 2019-02-05 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biouploader', '0001_initial'),
        ('drawing', '0002_auto_20190205_1853'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('representations', '0001_initial'),
        ('bioconverter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='converttosamplerequest',
            name='bioimage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biouploader.BioImage'),
        ),
        migrations.AddField(
            model_name='converttosamplerequest',
            name='converter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioconverter.Converter'),
        ),
        migrations.AddField(
            model_name='converttosamplerequest',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='converttosamplerequest',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representations.Experiment'),
        ),
        migrations.AddField(
            model_name='conversionrequest',
            name='bioimage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biouploader.BioImage'),
        ),
        migrations.AddField(
            model_name='conversionrequest',
            name='converter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioconverter.Converter'),
        ),
        migrations.AddField(
            model_name='conversionrequest',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversionrequest',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representations.Experiment'),
        ),
        migrations.AddField(
            model_name='conversionrequest',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.Sample'),
        ),
        migrations.AddField(
            model_name='conversing',
            name='bioserie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biouploader.BioSeries'),
        ),
        migrations.AddField(
            model_name='conversing',
            name='converter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioconverter.Converter'),
        ),
        migrations.AddField(
            model_name='conversing',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversing',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representations.Experiment'),
        ),
        migrations.AddField(
            model_name='bioimagefile',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bioimagefiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
