# Generated by Django 2.2.9 on 2020-01-31 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bioconverter', '0001_initial'),
        ('biouploader', '0001_initial'),
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.Experiment'),
        ),
        migrations.AddField(
            model_name='representation',
            name='inputrep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bioconverter.Representation'),
        ),
        migrations.AddField(
            model_name='representation',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representations', to='elements.Sample'),
        ),
        migrations.AddField(
            model_name='representation',
            name='zarr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.Zarr'),
        ),
        migrations.AddField(
            model_name='conversing',
            name='bioserie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biouploader.BioSeries'),
        ),
        migrations.AddField(
            model_name='conversing',
            name='converter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioconverter.Converter'),
        ),
        migrations.AddField(
            model_name='conversing',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversing',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.Experiment'),
        ),
    ]
