# Generated by Django 2.2.9 on 2020-01-22 16:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bioconverter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converter',
            name='channel',
            field=models.CharField(default=uuid.UUID('548697a7-6316-4e12-a800-5db5c016e8b4'), max_length=100, unique=True),
        ),
    ]
