# Generated by Django 2.2.9 on 2020-03-02 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioconverter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioseries',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bioseries', to='elements.Sample'),
        ),
    ]
