# Generated by Django 2.2.5 on 2019-09-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioconverter', '0002_auto_20190920_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='vid',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
