# Generated by Django 2.2.9 on 2020-01-31 12:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioconverter', '0002_auto_20200131_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converter',
            name='channel',
            field=models.CharField(default=uuid.UUID('8998a519-5435-4075-9c0d-324d68864ee8'), max_length=100, unique=True),
        ),
    ]
