# Generated by Django 2.2.9 on 2020-03-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioconverter', '0002_auto_20200302_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioimage',
            name='nodeid',
            field=models.CharField(default='iosnionsodin', max_length=2000),
            preserve_default=False,
        ),
    ]
