# Generated by Django 2.2.9 on 2020-01-22 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bioconverter', '0002_auto_20200122_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converter',
            name='channel',
            field=models.CharField(default=uuid.UUID('73dbbd86-01bb-4e73-8c3f-d9797e207f1b'), max_length=100, unique=True),
        ),
    ]
