# Generated by Django 2.2.6 on 2019-11-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioconverter', '0003_auto_20190920_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversing',
            name='status',
            field=models.CharField(default='STARTED', max_length=40),
        ),
    ]
