# Generated by Django 2.2.9 on 2020-02-12 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bioconverter', '0003_auto_20200131_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='type',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='converter',
            name='channel',
            field=models.CharField(default=uuid.UUID('85615223-4c5c-4061-b2b4-28b97aee3a23'), max_length=100, unique=True),
        ),
    ]
