# Generated by Django 2.2.9 on 2020-01-22 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bioconverter', '0003_auto_20200122_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converter',
            name='channel',
            field=models.CharField(default=uuid.UUID('d1cb59db-6af4-412b-8a99-ef5deb4db9ef'), max_length=100, unique=True),
        ),
    ]
