# Generated by Django 2.2.9 on 2020-02-12 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bioconverter', '0004_auto_20200212_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='chain',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
        migrations.AlterField(
            model_name='converter',
            name='channel',
            field=models.CharField(default=uuid.UUID('43f0a9e2-d756-4044-a689-40de555b32ac'), max_length=100, unique=True),
        ),
    ]
