# Generated by Django 2.2.7 on 2019-12-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioconverter', '0004_conversing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversing',
            name='statuscode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversing',
            name='statusmessage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
