# Generated by Django 2.2.9 on 2020-01-22 17:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bioconverter', '0004_auto_20200122_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converter',
            name='channel',
            field=models.CharField(default=uuid.UUID('041e1240-6561-4d0d-8099-1534d667ff16'), max_length=100, unique=True),
        ),
    ]
