# Generated by Django 2.2.9 on 2020-01-23 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bioconverter', '0005_auto_20200122_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converter',
            name='channel',
            field=models.CharField(default=uuid.UUID('3372592e-62df-49c2-a44b-f43529d25e79'), max_length=100, unique=True),
        ),
    ]
