# Generated by Django 2.2.9 on 2020-01-28 13:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bioconverter', '0007_auto_20200123_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converter',
            name='channel',
            field=models.CharField(default=uuid.UUID('5d2da403-2f95-467a-accd-31793719feda'), max_length=100, unique=True),
        ),
    ]
