# Generated by Django 2.2.5 on 2019-10-01 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elements', '0004_pandas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oracle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel', models.CharField(blank=True, max_length=100, null=True)),
                ('defaultsettings', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('querystring', models.TextField(blank=True, null=True)),
                ('nodeid', models.CharField(blank=True, max_length=400, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeid', models.CharField(blank=True, max_length=400, null=True)),
                ('override', models.BooleanField()),
                ('querystring', models.TextField(blank=True, null=True)),
                ('settings', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('error', models.CharField(blank=True, max_length=300, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.Experiment')),
                ('oracle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.Oracle')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.Question')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.Sample')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(blank=True, max_length=300, null=True)),
                ('nodeid', models.CharField(blank=True, max_length=400, null=True)),
                ('vid', models.CharField(max_length=4000)),
                ('shape', models.CharField(blank=True, max_length=400, null=True)),
                ('name', models.CharField(blank=True, max_length=4000, null=True)),
                ('key', models.CharField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('pandas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Pandas')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='answers.Question')),
            ],
        ),
    ]
