# Generated by Django 2.2.5 on 2019-10-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='hallo', max_length=500),
            preserve_default=False,
        ),
    ]
