# Generated by Django 2.2.5 on 2019-10-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_question_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answering',
            name='querystring',
        ),
    ]
