# Generated by Django 2.2.5 on 2019-10-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_remove_answering_querystring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answering',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='answering',
            name='sample',
        ),
    ]
