# Generated by Django 2.2.5 on 2019-09-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biouploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioimage',
            name='file',
            field=models.FileField(max_length=1000, upload_to='bioimages', verbose_name='bioimage'),
        ),
    ]
