# Generated by Django 2.2.7 on 2019-12-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biouploader', '0002_auto_20190921_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzing',
            name='statuscode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyzing',
            name='statusmessage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
