# Generated by Django 2.2.9 on 2020-01-22 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('biouploader', '0002_auto_20200122_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzer',
            name='channel',
            field=models.CharField(default=uuid.UUID('90947be2-8d23-462f-887c-e341fd193b12'), max_length=100, unique=True),
        ),
    ]
