# Generated by Django 2.0.9 on 2019-03-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biouploader', '0002_auto_20190311_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bioseries',
            name='vid',
        ),
    ]
