# Generated by Django 2.2.11 on 2020-03-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutaters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reflection',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='reflection',
            name='roi',
        ),
        migrations.RemoveField(
            model_name='reflection',
            name='sample',
        ),
        migrations.AddField(
            model_name='reflection',
            name='name',
            field=models.CharField(default='soinsoien', max_length=300),
            preserve_default=False,
        ),
    ]
