# Generated by Django 2.0.9 on 2019-02-05 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('representations', '0001_initial'),
        ('transformers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drawing', '0002_auto_20190205_1853'),
        ('mutaters', '0001_initial'),
        ('filterbank', '0002_auto_20190205_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representations.Experiment'),
        ),
        migrations.AddField(
            model_name='reflection',
            name='nifti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filterbank.Nifti'),
        ),
        migrations.AddField(
            model_name='reflection',
            name='roi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drawing.ROI'),
        ),
        migrations.AddField(
            model_name='reflection',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.Sample'),
        ),
        migrations.AddField(
            model_name='reflection',
            name='transformation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transformers.Transformation'),
        ),
        migrations.AddField(
            model_name='mutating',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mutating',
            name='mutator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutaters.Mutator'),
        ),
        migrations.AddField(
            model_name='mutating',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.Sample'),
        ),
        migrations.AddField(
            model_name='mutating',
            name='transformation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transformers.Transformation'),
        ),
    ]
