# Generated by Django 2.2.11 on 2020-03-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutaters', '0002_auto_20200309_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutating',
            name='sample',
        ),
    ]
