# Generated by Django 2.0.9 on 2019-02-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutaters', '0003_auto_20190209_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutater',
            name='nodeid',
        ),
        migrations.RemoveField(
            model_name='mutater',
            name='outputtype',
        ),
        migrations.AddField(
            model_name='mutater',
            name='inputmodel',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mutater',
            name='outputmodel',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mutater',
            name='channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
