# Generated by Django 2.0.9 on 2019-02-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutaters', '0004_auto_20190209_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mutating',
            old_name='mutator',
            new_name='mutater',
        ),
    ]
