# Generated by Django 2.2.6 on 2019-10-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='htmlfile',
            field=models.FileField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
