# Generated by Django 2.2.6 on 2019-10-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizers', '0002_auto_20191001_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizing',
            name='status',
            field=models.CharField(default='STARTED', max_length=40),
        ),
    ]
