# Generated by Django 2.2.7 on 2019-12-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larvik', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='LarvikJob',
        ),
    ]
