# Generated by Django 2.2.11 on 2020-03-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineroi',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
