# Generated by Django 2.2.9 on 2020-01-31 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamorphers', '0001_initial'),
        ('bioconverter', '0002_auto_20200131_1240'),
        ('elements', '0001_initial'),
        ('drawing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roi',
            name='display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metamorphers.Display'),
        ),
        migrations.AddField(
            model_name='roi',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.Experiment'),
        ),
        migrations.AddField(
            model_name='roi',
            name='experimentalgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elements.ExperimentalGroup'),
        ),
        migrations.AddField(
            model_name='roi',
            name='representation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bioconverter.Representation'),
        ),
        migrations.AddField(
            model_name='roi',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.Sample'),
        ),
    ]
