# Generated by Django 2.0.9 on 2019-02-05 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('representations', '0001_initial'),
        ('filterbank', '0001_initial'),
        ('drawing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representations.Experiment'),
        ),
        migrations.AddField(
            model_name='sample',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drawing.BioMeta'),
        ),
        migrations.AddField(
            model_name='roi',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roi',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representations.Experiment'),
        ),
        migrations.AddField(
            model_name='roi',
            name='representation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filterbank.Representation'),
        ),
        migrations.AddField(
            model_name='roi',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.Sample'),
        ),
    ]
