# Generated by Django 2.2.5 on 2019-09-20 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elements', '0001_initial'),
        ('metamorphers', '0001_initial'),
        ('bioconverter', '0002_auto_20190920_1249'),
        ('drawing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roi',
            name='display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metamorphers.Display'),
        ),
        migrations.AddField(
            model_name='roi',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.Experiment'),
        ),
        migrations.AddField(
            model_name='roi',
            name='representation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bioconverter.Representation'),
        ),
        migrations.AddField(
            model_name='roi',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.Sample'),
        ),
    ]
