# Generated by Django 2.2.9 on 2020-01-22 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bioconverter', '0002_auto_20200122_1615'),
        ('elements', '0001_initial'),
        ('drawing', '0001_initial'),
        ('metamorphers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roi',
            name='display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metamorphers.Display'),
        ),
        migrations.AddField(
            model_name='roi',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.Experiment'),
        ),
        migrations.AddField(
            model_name='roi',
            name='experimentalgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elements.ExperimentalGroup'),
        ),
        migrations.AddField(
            model_name='roi',
            name='representation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bioconverter.Representation'),
        ),
        migrations.AddField(
            model_name='roi',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.Sample'),
        ),
    ]
