# Generated by Django 2.2.6 on 2019-10-01 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_auto_20191001_1600'),
        ('drawing', '0002_auto_20190920_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='roi',
            name='experimentalgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elements.ExperimentalGroup'),
        ),
    ]
