# Generated by Django 2.0.9 on 2019-03-12 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biouploader', '0003_remove_bioseries_vid'),
        ('drawing', '0002_auto_20190205_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='bioseries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biouploader.BioSeries'),
        ),
    ]
