# Generated by Django 2.0.9 on 2019-03-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0003_sample_bioseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='roi',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
