# Generated by Django 2.2.1 on 2019-05-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0004_roi_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometa',
            name='json',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
