# Generated by Django 2.2.9 on 2020-01-22 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import larvik.discover


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='hash',
        ),
        migrations.AddField(
            model_name='node',
            name='hash',
            field=models.CharField(default=larvik.discover.createUniqeNodeName, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
