# Generated by Django 2.2.6 on 2019-10-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_foreignnodestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignnoderequest',
            name='origin',
            field=models.CharField(default='sdfsdf', max_length=300),
            preserve_default=False,
        ),
    ]
