# Generated by Django 2.2.9 on 2020-01-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_auto_20200122_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
