# Generated by Django 2.2.6 on 2019-11-20 14:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_external'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
