# Generated by Django 2.2.9 on 2020-01-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_node_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='type',
            new_name='variety',
        ),
    ]
