# Generated by Django 2.2.6 on 2019-11-20 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_auto_20191120_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='external',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
