# Generated by Django 2.2.6 on 2019-11-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0008_auto_20191120_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalrequest',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
