# Generated by Django 2.2.6 on 2019-11-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0009_auto_20191120_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
