# Generated by Django 2.2.6 on 2019-11-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0010_auto_20191120_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='external',
            name='ports',
            field=models.CharField(blank=True, max_length=7000, null=True),
        ),
    ]
