# Generated by Django 2.2.6 on 2019-11-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0013_externalrequest_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='external',
            name='origin',
            field=models.CharField(default='none', max_length=2000),
            preserve_default=False,
        ),
    ]
