# Generated by Django 2.2.7 on 2019-12-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0014_external_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='external',
            name='uniqueid',
            field=models.CharField(blank=True, max_length=400, null=True, unique=True),
        ),
    ]
