# Generated by Django 2.0.9 on 2019-02-05 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('representations', '0001_initial'),
        ('drawing', '0002_auto_20190205_1853'),
        ('filterbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representations.Experiment'),
        ),
        migrations.AddField(
            model_name='representation',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filterbank.AImage'),
        ),
        migrations.AddField(
            model_name='representation',
            name='nparray',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filterbank.NpArray'),
        ),
        migrations.AddField(
            model_name='representation',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representations', to='drawing.Sample'),
        ),
        migrations.AddField(
            model_name='parsing',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parsing',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representations.Experiment'),
        ),
        migrations.AddField(
            model_name='parsing',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filterbank.Filter'),
        ),
        migrations.AddField(
            model_name='parsing',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.Sample'),
        ),
        migrations.AddField(
            model_name='filtering',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filtering',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representations.Experiment'),
        ),
        migrations.AddField(
            model_name='filtering',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filterbank.Filter'),
        ),
        migrations.AddField(
            model_name='filtering',
            name='representation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filterbank.Representation'),
        ),
        migrations.AddField(
            model_name='filtering',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.Sample'),
        ),
    ]
