# Generated by Django 2.2.9 on 2020-01-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterbank', '0002_auto_20190920_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtering',
            name='statuscode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filtering',
            name='statusmessage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
