# Generated by Django 2.0.9 on 2019-04-03 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filterbank', '0002_auto_20190205_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='inputrep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filterbank.Representation'),
        ),
    ]
