# Generated by Django 2.0.9 on 2019-04-08 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filterbank', '0003_representation_inputrep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='inputrep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filterbank.Representation'),
        ),
    ]
