# Generated by Django 2.2.5 on 2019-09-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterbank', '0004_auto_20190408_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
