# Generated by Django 2.2.5 on 2019-09-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterbank', '0005_auto_20190904_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nparray',
            name='position',
            field=models.CharField(max_length=1000),
        ),
    ]
