# Generated by Django 2.2.5 on 2019-09-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterbank', '0006_auto_20190904_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nparray',
            name='file',
            field=models.FilePathField(max_length=1000),
        ),
    ]
